POST https://y1sfs3ink3.execute-api.us-east-1.amazonaws.com/Prod/election
userId:12345

###
GET https://y1sfs3ink3.execute-api.us-east-1.amazonaws.com/Prod/election/588b1512-8f77-4e77-bfea-cb4b7f20a373/candidates
userId:12345

###
POST https://y1sfs3ink3.execute-api.us-east-1.amazonaws.com/Prod/election/588b1512-8f77-4e77-bfea-cb4b7f20a373/candidates
userId:12345
Content-Type: application/json

{"electionId": "588b1512-8f77-4e77-bfea-cb4b7f20a373", "candidates": [{"value": "Candidate A", "candidateId": "aaaa"},{"value": "Candidate B", "candidateId": "bbbb"}]}
###
POST https://y1sfs3ink3.execute-api.us-east-1.amazonaws.com/Prod/election/588b1512-8f77-4e77-bfea-cb4b7f20a373/start
userId:12345
###
POST https://y1sfs3ink3.execute-api.us-east-1.amazonaws.com/Prod/election/588b1512-8f77-4e77-bfea-cb4b7f20a373/end
userId:12345
###
POST https://y1sfs3ink3.execute-api.us-east-1.amazonaws.com/Prod/election/588b1512-8f77-4e77-bfea-cb4b7f20a373/restart
userId:12345
###
GET https://y1sfs3ink3.execute-api.us-east-1.amazonaws.com/Prod/election/588b1512-8f77-4e77-bfea-cb4b7f20a373/settings
userId:12345
###
POST https://y1sfs3ink3.execute-api.us-east-1.amazonaws.com/Prod/election/588b1512-8f77-4e77-bfea-cb4b7f20a373/settings
userId:12345
Content-Type: application/json

{"electionId": "588b1512-8f77-4e77-bfea-cb4b7f20a373", "uniqueIdsPerUser": false, "userEmails": ["jqt3of5@gmail.com"], "electionName":  "My Election"}
###
POST https://y1sfs3ink3.execute-api.us-east-1.amazonaws.com/Prod/election/588b1512-8f77-4e77-bfea-cb4b7f20a373/vote
userId:12345
Content-Type: application/json

["aaaa","bbbb"]
###